package dev.eryalabs.lim

import android.content.Intent
import android.util.Base64
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.BeforeClass
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import java.nio.ByteBuffer
import java.nio.charset.CharacterCodingException
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets
import java.security.KeyFactory
import java.security.KeyPair
import java.security.KeyPairGenerator
import java.security.MessageDigest
import java.security.Signature
import java.security.interfaces.RSAPublicKey
import java.security.spec.X509EncodedKeySpec
import java.util.Random

/**
 * Every decoder in this library reads bytes another app chose. The other tests cover the
 * malformed shapes somebody thought of; this one covers the ones nobody did.
 *
 * The corpus is generated by a `java.util.Random` pinned to a fixed seed, so the few thousand
 * payloads below are the *same* few thousand payloads on every run and on every machine — a
 * failure here is reproducible from the log rather than from a lucky rerun. The generator is a
 * pure function of a per-case seed, every failure message carries that seed alongside the
 * payload itself, and `the corpus is byte-identical on every run` pins the whole corpus against
 * a digest so that neither of those claims can quietly stop being true.
 *
 * `java.util.Random` and not `SecureRandom`: this needs a *reproducible* sequence, which is the
 * one thing a cryptographic source refuses to give. No new dependency is involved either way.
 *
 * What is asserted is deliberately weak on values and strong on safety: nobody can say what
 * [Utils.decodeFields] *should* return for a byte-flipped payload, but everybody can say it
 * must not throw and must not hand back an object that NPEs when a client reads it.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class DecoderFuzzTest {

    // ── The corpus ───────────────────────────────────────────────────────

    private enum class Mutation {
        /** Cut the payload off part-way — the shape an interrupted IPC write leaves behind. */
        TRUNCATE,

        /** Replace one character with a structurally nasty one. */
        FLIP,

        /** Drop one character: unbalanced braces, broken escapes. */
        DELETE,

        /** Insert one character into the middle of a token. */
        INSERT,

        /** Repeat a slice, producing duplicate keys and stray fragments. */
        DUPLICATE,

        /** Swap a JSON string for a number, bool, null, array or object — a type confusion. */
        SWAP_TYPE,

        /** Hundreds of levels of nesting, alone and buried inside an otherwise valid payload. */
        NEST,

        /** A single value or key of up to 16k characters. */
        HUGE,

        /** Empty containers: `{}`, `[]`, `""`, an entry whose field map is empty. */
        EMPTY,

        /** Valid JSON of entirely the wrong shape — parses cleanly, means nothing here. */
        WRONG_SHAPE,

        /** Structural characters in an arbitrary order, including unpaired surrogates. */
        NOISE,
    }

    private data class Case(val kind: Mutation, val text: String)

    /**
     * Starting points for the mutators. These are the payloads the protocol actually produces,
     * so a one-character mutation lands *near* a valid document rather than in the middle of
     * noise — which is where the interesting decoder behaviour lives.
     */
    private val wellFormed = listOf(
        """{"name":{"value":"Ada Lovelace","type":"String"},"age":{"value":"36","type":"Integer"}}""",
        """{"id":"profile-1","publicKey":"MIIBIjANBgkq","fields":{"email":{"value":"ada@example.com","type":"Email"}}}""",
        """{"id":"profile-1","publicKey":"MIIBIjANBgkq"}""",
        """{"value":"v","type":"String"}""",
    )

    /** Valid JSON documents that are simply not what either decoder is looking for. */
    private val wrongShapes = listOf(
        "null", "42", "-0.0", "1e999", "true", "false", "\"just a string\"", "[]", "{}",
        "[1,2,3]",
        """[{"id":"x","publicKey":"k"}]""",
        """{"id":{"id":"x"},"publicKey":["k"]}""",
        """{"id":"x","publicKey":"k","fields":[{"value":"v"}]}""",
        """{"fields":{"a":{"value":["v"],"type":{"t":1}}}}""",
        """{"0":{"value":true,"type":7}}""",
        """{"id":null,"publicKey":null,"fields":null}""",
        // A null *entry* inside an otherwise valid field map. Seeded explicitly rather than
        // left to the mutators: no single-character mutation of the well-formed payloads
        // reaches it, and without it the null-field checks in `checkFields` never fire, which
        // would make them assertions that cannot fail.
        """{"a":null,"b":{"value":"v","type":"String"}}""",
        """{"id":"x","publicKey":"k","fields":{"a":null,"b":{"value":"v","type":"String"}}}""",
        """{"ID":"x","PUBLICKEY":"k"}""",
        """{"id":"x","publicKey":"k","fields":{"a":{"value":"v"},"a":{"value":"w"}}}""",
    )

    private val emptyContainers = listOf(
        "{}", "[]", "\"\"", "   ", "{\"\":{}}", "{\"\":{\"value\":\"\",\"type\":\"\"}}",
        """{"id":"","publicKey":"","fields":{}}""",
        // One identity blank and the other populated, both ways round. Without these the corpus
        // only ever blanks *both*, so a mutant that dropped one half of `decodeEntry`'s
        // blank-identity check would survive the half that was still there.
        """{"id":"","publicKey":"k","fields":{"a":{"value":"v","type":"String"}}}""",
        """{"id":"x","publicKey":"","fields":{"a":{"value":"v","type":"String"}}}""",
        """{"id":"   ","publicKey":"k","fields":{"a":{"value":"v","type":"String"}}}""",
        """{"id":"x","publicKey":"k","fields":{}}""",
        """{"id":"x","publicKey":"k","fields":{"":{"value":"","type":""}}}""",
    )

    // Code points spelled out numerically rather than typed literally: two of them (NUL and a
    // lone surrogate) cannot survive a round trip through a UTF-8 source file, and a corpus
    // whose contents depend on how this file was saved is not a reproducible corpus.
    private val nul = 0x0000.toChar()
    private val eAcute = 0x00E9.toChar()
    private val bidiOverride = 0x202E.toChar()

    /** No `String` can encode this to UTF-8, so it also exercises the lossy path to bytes. */
    private val loneSurrogate = 0xD83D.toChar()

    /**
     * Characters picked to break structure rather than to look random: JSON metacharacters,
     * whitespace, NUL, a bidi override, a multi-byte letter and an unpaired surrogate.
     */
    private val nastyChars = buildString {
        append("{}[]\",:\\/ \n\t'`0-+eE")
        append(nul).append(eAcute).append(bidiOverride).append(loneSurrogate)
    }.toCharArray()

    /** Fillers for the oversized payloads: plain, escape-bearing, multi-byte, and NUL. */
    private val hugeChars = charArrayOf('x', '\\', eAcute, nul)

    private val nonStringTokens = listOf(
        "123", "-1", "true", "false", "null", "[]", "{}", """["v"]""", """{"value":"v"}""", "1e999",
    )

    private val quoted = Regex("\"[^\"]*\"")

    /**
     * Build one payload from one seed. Pure: the same seed yields the same payload for ever,
     * which is what makes a failure message actionable without a rerun.
     */
    private fun caseFor(seed: Long): Case {
        val rnd = Random(seed)
        val kind = Mutation.values()[rnd.nextInt(Mutation.values().size)]
        val base = wellFormed[rnd.nextInt(wellFormed.size)]
        val text = when (kind) {
            Mutation.TRUNCATE -> base.substring(0, rnd.nextInt(base.length + 1))

            Mutation.FLIP -> {
                val i = rnd.nextInt(base.length)
                base.substring(0, i) + nastyChars[rnd.nextInt(nastyChars.size)] + base.substring(i + 1)
            }

            Mutation.DELETE -> {
                val i = rnd.nextInt(base.length)
                base.substring(0, i) + base.substring(i + 1)
            }

            Mutation.INSERT -> {
                val i = rnd.nextInt(base.length + 1)
                base.substring(0, i) + nastyChars[rnd.nextInt(nastyChars.size)] + base.substring(i)
            }

            Mutation.DUPLICATE -> {
                val from = rnd.nextInt(base.length)
                val to = from + rnd.nextInt(base.length - from + 1)
                base.substring(0, to) + base.substring(from, to) + base.substring(to)
            }

            Mutation.SWAP_TYPE -> {
                // Deliberately allowed to hit a *key* as well as a value: `{123:...}` is exactly
                // the sort of thing a buggy encoder on the far side would emit.
                val matches = quoted.findAll(base).toList()
                val m = matches[rnd.nextInt(matches.size)]
                base.substring(0, m.range.first) +
                    nonStringTokens[rnd.nextInt(nonStringTokens.size)] +
                    base.substring(m.range.last + 1)
            }

            Mutation.NEST -> {
                // The range deliberately straddles the depth at which the JSON parser gives up
                // (measured between 200 and 1000 on this toolchain): both sides are interesting,
                // and the far side is where a recursive-descent parser would blow the stack.
                // That failure mode is the reason the fuzz loop catches `Throwable` and not
                // `Exception` — `StackOverflowError` is an `Error`, so every `catch (_: Exception)`
                // in `Utils` would let it straight through to the client app.
                val depth = 1 + rnd.nextInt(1200)
                val asArray = rnd.nextBoolean()
                val core = (if (asArray) "[" else "{\"a\":").repeat(depth) +
                    "1" +
                    (if (asArray) "]" else "}").repeat(depth)
                when (rnd.nextInt(3)) {
                    0 -> core
                    1 -> """{"id":"x","publicKey":"k","fields":$core}"""
                    else -> """{"a":{"value":$core,"type":"String"}}"""
                }
            }

            Mutation.HUGE -> {
                val filler = hugeChars[rnd.nextInt(hugeChars.size)]
                    .toString()
                    .repeat(1 shl (6 + rnd.nextInt(9)))
                when (rnd.nextInt(4)) {
                    0 -> """{"id":"$filler","publicKey":"k"}"""
                    1 -> """{"id":"x","publicKey":"$filler"}"""
                    2 -> """{"$filler":{"value":"v","type":"String"}}"""
                    else -> """{"a":{"value":"$filler","type":"$filler"}}"""
                }
            }

            Mutation.EMPTY -> emptyContainers[rnd.nextInt(emptyContainers.size)]

            Mutation.WRONG_SHAPE -> wrongShapes[rnd.nextInt(wrongShapes.size)]

            Mutation.NOISE -> buildString {
                repeat(rnd.nextInt(64)) { append(nastyChars[rnd.nextInt(nastyChars.size)]) }
            }
        }
        return Case(kind, text)
    }

    // ── Failure reporting ────────────────────────────────────────────────
    //
    // Built only once something has already gone wrong. A fuzz loop that formats a message for
    // every assertion spends its whole budget formatting messages nobody reads, so each check
    // below is an `if (...) bail(...)` rather than an `assertX(message, ...)`.

    private fun report(what: String, index: Int, seed: Long, case: Case): String = buildString {
        append(what).append('\n')
        append("  masterSeed = ").append(MASTER_SEED).append("L\n")
        append("  case       = #").append(index).append(" of ").append(CASES).append('\n')
        append("  caseSeed   = ").append(seed).append("L   (reproduce with caseFor(")
            .append(seed).append("L))\n")
        append("  mutation   = ").append(case.kind).append('\n')
        append("  length     = ").append(case.text.length).append(" chars\n")
        append("  payload    = ").append(printable(case.text))
    }

    /** Escape everything unprintable so a payload survives a log file, and cap the length. */
    private fun printable(text: String): String {
        val capped = text.take(PAYLOAD_PREVIEW)
        val escaped = buildString(capped.length) {
            capped.forEach { c ->
                if (c in ' '..'~') {
                    append(c)
                } else {
                    append("\\u")
                    append(HEX[(c.code shr 12) and 0xF])
                    append(HEX[(c.code shr 8) and 0xF])
                    append(HEX[(c.code shr 4) and 0xF])
                    append(HEX[c.code and 0xF])
                }
            }
        }
        return if (text.length > PAYLOAD_PREVIEW) {
            escaped + "... (+" + (text.length - PAYLOAD_PREVIEW) + " more chars)"
        } else {
            escaped
        }
    }

    // ── Safety checks ────────────────────────────────────────────────────

    /**
     * A decoded field map must be safe to *use*, not merely non-null. Gson builds [TypedField]
     * through `Unsafe`, so a declared-non-null property can genuinely hold null at runtime and
     * Kotlin inserts no check when reading it — hence the `Any?` comparisons, which keep saying
     * something even if those properties are one day declared nullable, followed by the real
     * calls a client would make on the result.
     *
     * @return the number of value characters actually dereferenced, so the caller can prove
     *         these checks were not vacuous.
     */
    private fun checkFields(fields: Map<String, TypedField>, bail: (String) -> Nothing): Int {
        var chars = 0
        fields.forEach { (key, field) ->
            if ((key as Any?) == null) bail("decodeFields returned a null key")
            if ((field as Any?) == null) bail("decodeFields returned a null TypedField for key '$key'")
            if ((field.value as Any?) == null) bail("TypedField.value is null for key '$key'")
            if ((field.type as Any?) == null) bail("TypedField.type is null for key '$key'")
            chars += field.value.length
            // Wrapped like `toString` below rather than called bare: an escaping throw here
            // would reach the log without the seed and payload, and a failure nobody can
            // reproduce from the log is the one thing this test is built to avoid.
            val normalized = try {
                FieldType.normalize(field.type)
            } catch (t: Throwable) {
                bail("FieldType.normalize threw ${t.javaClass.name}: ${t.message} for key '$key'")
            }
            if (normalized.isEmpty()) {
                bail("FieldType.normalize returned empty for key '$key' (type='${field.type}')")
            }
            try {
                field.toString()
            } catch (t: Throwable) {
                bail("TypedField.toString() threw ${t.javaClass.name}: ${t.message} for key '$key'")
            }
        }
        return chars
    }

    /**
     * A non-null [Entry] from [Utils.decodeEntry] is documented as fully populated and safe to
     * dereference, including a non-blank identity — the strictest promise this library makes
     * about anything it decoded.
     */
    private fun checkEntry(entry: Entry, bail: (String) -> Nothing): Int {
        if ((entry.id as Any?) == null) bail("decodeEntry returned an Entry with a null id")
        if ((entry.publicKey as Any?) == null) bail("decodeEntry returned an Entry with a null publicKey")
        if ((entry.fields as Any?) == null) bail("decodeEntry returned an Entry with a null fields map")
        if (entry.id.isBlank()) bail("decodeEntry returned an Entry with a blank id")
        if (entry.publicKey.isBlank()) bail("decodeEntry returned an Entry with a blank publicKey")
        try {
            entry.toString()
        } catch (t: Throwable) {
            bail("Entry.toString() threw ${t.javaClass.name}: ${t.message}")
        }
        return entry.id.length + entry.publicKey.length + checkFields(entry.fields, bail)
    }

    // ── The fuzz run ─────────────────────────────────────────────────────

    @Test
    fun `no mutated payload makes a decoder throw or yield something unsafe`() {
        val master = Random(MASTER_SEED)
        val kinds = linkedMapOf<Mutation, Int>()
        var nonEmptyFields = 0
        var decodedEntries = 0
        var entriesWithFields = 0
        var charsRead = 0L

        repeat(CASES) { index ->
            val seed = master.nextLong()
            val case = caseFor(seed)
            kinds[case.kind] = (kinds[case.kind] ?: 0) + 1

            fun bail(what: String, cause: Throwable? = null): Nothing =
                throw AssertionError(report(what, index, seed, case), cause)

            val fields = try {
                Utils.decodeFields(case.text)
            } catch (t: Throwable) {
                bail("decodeFields threw ${t.javaClass.name}: ${t.message}", t)
            }
            charsRead += checkFields(fields) { bail(it) }
            if (fields.isNotEmpty()) nonEmptyFields++

            val entry = try {
                Utils.decodeEntry(case.text)
            } catch (t: Throwable) {
                bail("decodeEntry threw ${t.javaClass.name}: ${t.message}", t)
            }
            if (entry != null) {
                charsRead += checkEntry(entry) { bail(it) }
                decodedEntries++
                if (entry.fields.isNotEmpty()) entriesWithFields++
            }

            // Into the verifier through Base64, in all three argument positions. Every one of
            // these must be false: the payload is text, and none of it is a signature over
            // NONCE by the private key of `keyPair`.
            val bytes = case.text.toByteArray()

            val asSignature = try {
                Utils.verifySignature(publicKeyBase64, NONCE, bytes)
            } catch (t: Throwable) {
                bail("verifySignature threw ${t.javaClass.name} on a fuzzed signature", t)
            }
            if (asSignature) bail("verifySignature ACCEPTED a fuzzed payload as a signature")

            val asKey = try {
                Utils.verifySignature(Base64.encodeToString(bytes, Base64.DEFAULT), NONCE, signature)
            } catch (t: Throwable) {
                bail("verifySignature threw ${t.javaClass.name} on a fuzzed public key", t)
            }
            if (asKey) bail("verifySignature ACCEPTED a fuzzed payload as a public key")

            val asNonce = try {
                Utils.verifySignature(publicKeyBase64, bytes, signature)
            } catch (t: Throwable) {
                bail("verifySignature threw ${t.javaClass.name} on a fuzzed nonce", t)
            }
            if (asNonce) bail("verifySignature ACCEPTED a signature made over a different nonce")
        }

        // Non-vacuity. Without these, the whole test passes against a `decodeFields` that
        // returns `emptyMap()` and a `decodeEntry` that returns `null` for everything — the two
        // mutants a safety-only fuzz run is blindest to. The floors sit far below what this
        // corpus actually produces (the counts are in the messages), so they pin "the generator
        // still reaches the interesting paths" rather than an exact census.
        assertEquals(
            "every mutation kind must be exercised; got $kinds",
            Mutation.values().toSet(),
            kinds.keys,
        )
        assertTrue(
            "the corpus must decode some non-empty field maps, else the field checks are " +
                "vacuous; got $nonEmptyFields of $CASES",
            nonEmptyFields > 200,
        )
        assertTrue(
            "the corpus must decode some real entries, else checkEntry never runs; got " +
                "$decodedEntries of $CASES",
            decodedEntries > 100,
        )
        assertTrue(
            "some decoded entries must carry fields, else the nested map is never checked; " +
                "got $entriesWithFields",
            entriesWithFields > 20,
        )
        assertTrue(
            "the safety checks must have dereferenced real characters; got $charsRead",
            charsRead > 10_000L,
        )
    }

    /**
     * The same corpus, one boundary further out.
     *
     * The run above feeds the decoders directly. But a client never calls them directly — the
     * hostile JSON reaches it *through* a result intent, and the parsers are what unwrap it.
     * They decode the same payloads across the same IPC boundary, and T8's text named only the
     * three decoders, so nothing had ever pushed a mutated payload through them. This closes
     * that: every extra each parser reads gets the fuzzed text in turn — the share-result
     * parser included, from the task that added it.
     *
     * `matchesRequestCode` and `isNonceFresh` ride along here for the same reason — both take
     * data another app chose, and neither had ever seen an input nobody thought of. What their
     * arms carry is throw-safety over unplanned bytes and nothing more: every corpus payload
     * opens with a JSON structural character, so the eight bytes `isNonceFresh` reads as a
     * timestamp are always a far-future one and the fresh branch is never reached from the
     * corpus. Their real behaviour is pinned in `NonceTest` and `RequestCodeTest`. The two
     * controls after the loop are what stop these arms from passing against a function that
     * returns a constant.
     *
     * The security property is the last one below and it is the reason this is not merely a
     * crash test: no mutated payload, in any position, may produce a result that authenticates
     * against the real key and nonce.
     */
    @Test
    fun `no mutated payload makes a result parser throw or yield something unsafe`() {
        val master = Random(MASTER_SEED)
        val genuineSignature = Base64.encodeToString(signature, Base64.DEFAULT)
        var signResults = 0
        var queryResults = 0
        var shareResults = 0
        var nonEmptyParsedFields = 0
        var charsRead = 0

        repeat(CASES) { index ->
            val seed = master.nextLong()
            val case = caseFor(seed)

            fun bail(what: String, cause: Throwable? = null): Nothing =
                throw AssertionError(report(what, index, seed, case), cause)

            fun intentOf(vararg extras: Pair<String, String>) = Intent().apply {
                extras.forEach { (key, value) -> putExtra(key, value) }
            }

            // The fuzzed text as a disclosed field payload, behind a signature that is real —
            // so parsing gets past the signature gate and the field decoding is what is under
            // test. A malformed payload here is documented as non-fatal, so the result must
            // come back and must still be safe to read.
            val signed = try {
                Utils.parseSignChallengeResult(
                    intentOf(
                        Utils.EXTRA_SIGNATURE to genuineSignature,
                        Utils.EXTRA_FIELDS_JSON to case.text,
                        Utils.EXTRA_ALGORITHM to case.text,
                        Utils.EXTRA_SHARE_REQUEST_CODE to case.text,
                    ),
                )
            } catch (t: Throwable) {
                bail("parseSignChallengeResult threw ${t.javaClass.name}: ${t.message}", t)
            }
            if (signed == null) bail("parseSignChallengeResult discarded a genuine signature")
            signResults++
            charsRead += checkFields(signed.fields) { bail(it) }
            if (signed.fields.isNotEmpty()) nonEmptyParsedFields++
            try {
                signed.toString()
            } catch (t: Throwable) {
                bail("SignChallengeResult.toString() threw ${t.javaClass.name}: ${t.message}", t)
            }

            // The fuzzed text as the signature itself. Anything that survives the Base64 gate
            // must be non-empty bytes — an empty signature is the shape T3 found could arrive
            // looking like an answer.
            val forged = try {
                Utils.parseSignChallengeResult(intentOf(Utils.EXTRA_SIGNATURE to case.text))
            } catch (t: Throwable) {
                bail("parseSignChallengeResult threw ${t.javaClass.name} on a fuzzed signature", t)
            }
            if (forged != null && forged.signature.isEmpty()) {
                bail("parseSignChallengeResult returned a result carrying an empty signature")
            }
            if (forged != null && forged.isVerified(publicKeyBase64, NONCE)) {
                bail("a fuzzed payload AUTHENTICATED as a signature over the challenge")
            }

            val query = try {
                Utils.parseQueryResult(
                    intentOf(
                        Utils.EXTRA_QUERY_RESULT_FIELDS to case.text,
                        Utils.EXTRA_PUBLIC_KEY to case.text,
                        Utils.EXTRA_SHARE_REQUEST_CODE to case.text,
                    ),
                )
            } catch (t: Throwable) {
                bail("parseQueryResult threw ${t.javaClass.name}: ${t.message}", t)
            }
            if (query != null) {
                queryResults++
                charsRead += checkFields(query.fields) { bail(it) }
                if (query.fields.isNotEmpty()) nonEmptyParsedFields++
                try {
                    query.toString()
                } catch (t: Throwable) {
                    bail("QueryResult.toString() threw ${t.javaClass.name}: ${t.message}", t)
                }
            } else if (case.text.isNotBlank()) {
                bail("parseQueryResult returned null for an intent carrying three non-blank extras")
            }

            // The share acknowledgement, through the same three positions its own flow defines.
            val share = try {
                Utils.parseShareResult(
                    intentOf(
                        Utils.EXTRA_PUBLIC_KEY to case.text,
                        Utils.EXTRA_FIELDS_JSON to case.text,
                        Utils.EXTRA_SHARE_REQUEST_CODE to case.text,
                    ),
                )
            } catch (t: Throwable) {
                bail("parseShareResult threw ${t.javaClass.name}: ${t.message}", t)
            }
            if (share != null) {
                shareResults++
                charsRead += checkFields(share.fields) { bail(it) }
                if (share.fields.isNotEmpty()) nonEmptyParsedFields++
                try {
                    share.toString()
                } catch (t: Throwable) {
                    bail("ShareResult.toString() threw ${t.javaClass.name}: ${t.message}", t)
                }
            } else if (case.text.isNotBlank()) {
                bail("parseShareResult returned null for an intent carrying three non-blank extras")
            }

            // Correlation. The fuzzed code is a token the *sender* chose, so it may only ever
            // match a caller who supplied that exact string — and never the caller who supplied
            // one of their own.
            val correlated = try {
                Utils.matchesRequestCode(intentOf(Utils.EXTRA_SHARE_REQUEST_CODE to case.text), KNOWN_CODE)
            } catch (t: Throwable) {
                bail("matchesRequestCode threw ${t.javaClass.name}: ${t.message}", t)
            }
            if (correlated && case.text != KNOWN_CODE) {
                bail("matchesRequestCode matched a payload that is not the expected code")
            }

            // Freshness, over bytes nobody designed. A nonce reaches a vault from a peer app.
            val fresh = try {
                Utils.isNonceFresh(case.text.toByteArray(), 60_000, now = FUZZ_CLOCK)
            } catch (t: Throwable) {
                bail("isNonceFresh threw ${t.javaClass.name}: ${t.message}", t)
            }
            if (fresh) bail("isNonceFresh accepted a text payload as a nonce issued in the last minute")
        }

        // The two controls the arms above cannot supply for themselves. Both of those checks are
        // satisfied by a function that returns a constant `false`, and a verifier that always
        // says no is not a verifier — so each is paired with the one input it must accept.
        assertTrue(
            "isNonceFresh must accept a genuine fresh nonce, else its fuzz arm passes against " +
                "a constant false",
            Utils.isNonceFresh(Utils.generateNonce(now = FUZZ_CLOCK), 60_000, now = FUZZ_CLOCK),
        )
        assertTrue(
            "matchesRequestCode must match the expected code, else its fuzz arm passes against " +
                "a constant false",
            Utils.matchesRequestCode(
                Intent().apply { putExtra(Utils.EXTRA_SHARE_REQUEST_CODE, KNOWN_CODE) },
                KNOWN_CODE,
            ),
        )

        // Non-vacuity. Without these the test passes against parsers that return null for
        // everything — and the sign-challenge arm in particular is asserted to be *total*: a
        // genuine signature must survive every payload the corpus can put beside it.
        assertEquals(
            "a genuine signature must parse regardless of what else is in the intent",
            CASES,
            signResults,
        )
        assertTrue(
            "the corpus must parse some non-empty field maps through the parsers, else the " +
                "field checks are vacuous; got $nonEmptyParsedFields",
            nonEmptyParsedFields > 200,
        )
        assertTrue(
            "the corpus must produce some query results; got $queryResults of $CASES",
            queryResults > 2000,
        )
        assertTrue(
            "the corpus must produce some share results; got $shareResults of $CASES",
            shareResults > 2000,
        )
        assertTrue(
            "the safety checks must have dereferenced real characters; got $charsRead",
            charsRead > 10_000,
        )
    }

    /**
     * The same corpus, into the request parsers — the boundary where the *vault* stands.
     *
     * A request intent is the one thing any installed app can fire at a vault unprovoked, so
     * these three parsers face the most hostile input in the protocol. Each required and
     * optional extra gets the fuzzed text in turn, and two structural properties ride along:
     * the share parser's acceptance must agree exactly with [Utils.decodeEntry] (it is
     * documented as the same bar), and no intent carrying a non-blank entry payload may ever
     * parse as a query — the routing line `RequestParsingTest` pins with designed inputs,
     * held here against inputs nobody designed.
     */
    @Test
    fun `no mutated payload makes a request parser throw or yield something unsafe`() {
        val master = Random(MASTER_SEED)
        var shareRequests = 0
        var queryRequests = 0
        var signRequests = 0
        var charsRead = 0

        repeat(CASES) { index ->
            val seed = master.nextLong()
            val case = caseFor(seed)

            fun bail(what: String, cause: Throwable? = null): Nothing =
                throw AssertionError(report(what, index, seed, case), cause)

            fun intentOf(vararg extras: Pair<String, String>) = Intent().apply {
                extras.forEach { (key, value) -> putExtra(key, value) }
            }

            // The fuzzed text as the entry payload, with the optional extras fuzzed too.
            val share = try {
                Utils.parseShareRequest(
                    intentOf(
                        Utils.EXTRA_ENTRY_JSON to case.text,
                        Utils.EXTRA_SHARE_REQUEST_CODE to case.text,
                        Utils.EXTRA_PROTOCOL_VERSION to case.text,
                    ),
                )
            } catch (t: Throwable) {
                bail("parseShareRequest threw ${t.javaClass.name}: ${t.message}", t)
            }
            if (share != null) {
                shareRequests++
                charsRead += checkEntry(share.entry) { bail(it) }
                try {
                    share.toString()
                } catch (t: Throwable) {
                    bail("ShareRequest.toString() threw ${t.javaClass.name}: ${t.message}", t)
                }
            }
            if ((share != null) != (Utils.decodeEntry(case.text) != null)) {
                bail("parseShareRequest's acceptance disagrees with decodeEntry")
            }

            // The routing property under fuzz: a non-blank entry payload makes the intent a
            // share, so the query parser must refuse it no matter what else it carries.
            val hijacked = try {
                Utils.parseQueryRequest(
                    intentOf(
                        Utils.EXTRA_ENTRY_JSON to case.text,
                        Utils.EXTRA_PUBLIC_KEY to "PUBLIC-KEY-BASE64",
                    ),
                )
            } catch (t: Throwable) {
                bail("parseQueryRequest threw ${t.javaClass.name} on a share-shaped intent", t)
            }
            if (hijacked != null && case.text.isNotBlank()) {
                bail("a query request was parsed out of an intent carrying an entry payload")
            }

            val query = try {
                Utils.parseQueryRequest(
                    intentOf(
                        Utils.EXTRA_PUBLIC_KEY to case.text,
                        Utils.EXTRA_SHARE_REQUEST_CODE to case.text,
                        Utils.EXTRA_PROTOCOL_VERSION to case.text,
                    ),
                )
            } catch (t: Throwable) {
                bail("parseQueryRequest threw ${t.javaClass.name}: ${t.message}", t)
            }
            if (query != null) {
                queryRequests++
                if (query.publicKey != case.text) {
                    bail("the parsed public key is not the one that was sent")
                }
                try {
                    query.toString()
                } catch (t: Throwable) {
                    bail("QueryRequest.toString() threw ${t.javaClass.name}: ${t.message}", t)
                }
            } else if (case.text.isNotBlank()) {
                bail("parseQueryRequest returned null for a non-blank public key")
            }

            val sign = try {
                Utils.parseSignChallengeRequest(
                    intentOf(
                        Utils.EXTRA_PUBLIC_KEY to case.text,
                        Utils.EXTRA_NONCE to case.text,
                        Utils.EXTRA_NONCE_FORMAT to case.text,
                        Utils.EXTRA_SHARE_REQUEST_CODE to case.text,
                    ),
                )
            } catch (t: Throwable) {
                bail("parseSignChallengeRequest threw ${t.javaClass.name}: ${t.message}", t)
            }
            if (sign != null) {
                signRequests++
                if (sign.nonce.isEmpty()) {
                    bail("parseSignChallengeRequest returned a request carrying an empty nonce")
                }
                if (sign.nonceFormat != null && sign.nonceFormat != case.text) {
                    bail("the nonce format did not travel verbatim")
                }
                try {
                    sign.toString()
                } catch (t: Throwable) {
                    bail("SignChallengeRequest.toString() threw ${t.javaClass.name}: ${t.message}", t)
                }
            }
        }

        // Non-vacuity. The share floor mirrors the decoder run's `decodedEntries > 100`
        // (same inputs, same decode); the query floor mirrors `queryResults > 2000` (same
        // non-blank criterion); the sign floor sits far below the measured count — most
        // payloads keep enough Base64-alphabet characters to decode to at least one byte.
        assertTrue(
            "the corpus must produce some share requests, else checkEntry never runs here; " +
                "got $shareRequests of $CASES",
            shareRequests > 100,
        )
        assertTrue(
            "the corpus must produce some query requests; got $queryRequests of $CASES",
            queryRequests > 2000,
        )
        assertTrue(
            "the corpus must produce some sign-challenge requests, else the nonce gate is " +
                "never exercised on accepted input; got $signRequests of $CASES",
            signRequests > 500,
        )
        assertTrue(
            "the safety checks must have dereferenced real characters; got $charsRead",
            charsRead > 1_000,
        )
    }

    /**
     * The same corpus, into the signing-oracle guard.
     *
     * [Utils.isStatementPreImage] is what a vault calls on a nonce another app chose, so it sees
     * whatever that app sends — and it is a *refusal* predicate, which makes a false positive
     * the expensive direction: every one of these refuses a signature the client legitimately
     * asked for. None of the corpus is a statement pre-image, so none of it may be reported as
     * one, and none of it may throw.
     *
     * The arm rides the existing corpus deliberately: nothing here edits the generator, so
     * [CORPUS_DIGEST] does not move. Paired with the genuine pre-image after the loop, without
     * which this passes unchanged against a predicate hardcoded to `false`.
     */
    @Test
    fun `no mutated payload is mistaken for a statement pre-image`() {
        val master = Random(MASTER_SEED)
        var decodedToBytes = 0

        repeat(CASES) { index ->
            val seed = master.nextLong()
            val case = caseFor(seed)

            fun bail(what: String, cause: Throwable? = null): Nothing =
                throw AssertionError(report(what, index, seed, case), cause)

            val claimed = try {
                Utils.isStatementPreImage(case.text.toByteArray())
            } catch (t: Throwable) {
                bail("isStatementPreImage threw ${t.javaClass.name}: ${t.message}", t)
            }
            if (claimed) bail("isStatementPreImage reported a fuzzed payload as a statement")

            // Also through Base64, the shape a nonce actually arrives in: a vault reads the
            // decoded bytes, not the text, and the decoder skips characters outside its alphabet
            // rather than rejecting them — so the bytes it yields are not the ones sent.
            val decoded = try {
                Base64.decode(case.text, Base64.DEFAULT)
            } catch (_: Exception) {
                ByteArray(0)
            }
            if (decoded.size >= Utils.STATEMENT_DOMAIN_V1.length) decodedToBytes++
            val claimedDecoded = try {
                Utils.isStatementPreImage(decoded)
            } catch (t: Throwable) {
                bail("isStatementPreImage threw ${t.javaClass.name} on decoded bytes", t)
            }
            if (claimedDecoded) bail("isStatementPreImage reported decoded fuzz as a statement")
        }

        // The floor for the Base64 half specifically. A failed decode lands on `ByteArray(0)`,
        // which the predicate refuses for the same reason it refuses everything else here — so
        // without this count, a platform decoder that threw on all 3000 payloads would leave that
        // half asserting nothing while still passing. Counted at the prefix length rather than at
        // one byte, because anything shorter short-circuits on `isStatementPreImage`'s length
        // guard and never reaches the byte comparison: a floor of "decoded to something" would be
        // the same vacuity one level down. The threshold matches the sign-request arm's, and the
        // same decode gates `EXTRA_NONCE` there, so it holds with margin on this pinned corpus.
        assertTrue(
            "the corpus must decode to bytes long enough to reach the prefix comparison, else " +
                "the Base64 half of this arm only ever exercises the length guard; got " +
                "$decodedToBytes of $CASES",
            decodedToBytes > 500,
        )

        // The non-vacuity floor every other arm in this file carries: a predicate that always
        // says no would satisfy the whole loop above.
        assertTrue(
            "isStatementPreImage must recognise a genuine pre-image, else its fuzz arm passes " +
                "against a constant false",
            Utils.isStatementPreImage(
                Utils.rotationStatementBytes(
                    RotationStatement("K-OLD", "K-NEW", "rot-0001", 1L, 2L),
                ),
            ),
        )
    }

    /**
     * The reproducibility claim, pinned rather than described. `java.util.Random` is specified
     * bit-for-bit by the JDK, so this digest is the same on every machine and every run; if an
     * edit to the generator changes it, that is a deliberate act and this constant moves in the
     * same commit. Without it, "identical input on every run" is a comment nobody re-checks.
     *
     * The payload is hashed as UTF-16 code units rather than through `toByteArray()`, which
     * would encode to UTF-8. That is not pedantry: no `String` can encode a lone surrogate, so
     * UTF-8 replaces [loneSurrogate] with `'?'` — and the digest would then be blind to a
     * generator edit that swapped that character for a literal `'?'`, which is precisely one of
     * the two characters this corpus deliberately carries and cannot round-trip.
     */
    @Test
    fun `the corpus is byte-identical on every run`() {
        val digest = MessageDigest.getInstance("SHA-256")
        val master = Random(MASTER_SEED)
        repeat(CASES) {
            val case = caseFor(master.nextLong())
            digest.update(case.kind.name.toByteArray())
            case.text.forEach { c ->
                digest.update((c.code shr 8).toByte())
                digest.update((c.code and 0xFF).toByte())
            }
        }
        assertEquals(
            "the fuzz corpus changed; update CORPUS_DIGEST only if the generator was edited " +
                "deliberately",
            CORPUS_DIGEST,
            hex(digest.digest()),
        )
    }

    /**
     * Supports the fuzzed-nonce arm of the run above. A `String` always encodes to *valid*
     * UTF-8, so if [NONCE] is not valid UTF-8 then no payload in the corpus can encode to it,
     * and that flat "must be false" cannot be tripped by a payload which happens to be the
     * genuine challenge.
     */
    @Test
    fun `the challenge nonce is unreachable from any text payload`() {
        val decoder = StandardCharsets.UTF_8.newDecoder()
            .onMalformedInput(CodingErrorAction.REPORT)
            .onUnmappableCharacter(CodingErrorAction.REPORT)
        val rejected = try {
            decoder.decode(ByteBuffer.wrap(NONCE))
            false
        } catch (_: CharacterCodingException) {
            true
        }
        assertTrue("NONCE must not be valid UTF-8, or the fuzzed-nonce check is unsound", rejected)
    }

    /**
     * Exhaustive rather than sampled: every one of the 2048 bits of a genuine signature, flipped
     * one at a time. These are the closest thing to a forgery the fuzzer can construct — bytes
     * that *were* a valid signature a moment ago — and not one of them may verify.
     */
    @Test
    fun `every single-bit flip of a genuine signature is rejected`() {
        var flips = 0
        signature.indices.forEach { byteIndex ->
            for (bit in 0..7) {
                val tampered = signature.copyOf()
                tampered[byteIndex] = (tampered[byteIndex].toInt() xor (1 shl bit)).toByte()
                flips++
                if (Utils.verifySignature(publicKeyBase64, NONCE, tampered)) {
                    throw AssertionError(
                        "a signature with bit $bit of byte $byteIndex flipped still verified",
                    )
                }
            }
        }
        assertEquals("every bit of a 2048-bit signature should have been flipped", 2048, flips)
        assertTrue(
            "control: the untampered signature must still verify",
            Utils.verifySignature(publicKeyBase64, NONCE, signature),
        )
    }

    /**
     * Mutating the *key* rather than the signature. The assertion is not a flat "never
     * verifies", because sometimes it legitimately must, for two separate reasons: Android's
     * Base64 decoder skips characters outside the alphabet and drops the spare bits of a final
     * group, so a mutation can decode to exactly the bytes it started from (the asymmetry
     * [Utils.validateEntry] documents); and a mutation can land in the DER wrapper rather than
     * in the key material, producing *different bytes that denote the same RSA key* (see
     * `a key whose AlgorithmIdentifier OID was mutated is still the same RSA key`).
     *
     * So the property is stated over the key, not over the bytes: whatever a mutation decodes
     * to, if it verifies then it must carry the same modulus and public exponent as the real
     * key. That — not byte equality — is what "one key authenticating for another" means, and
     * it is pinned from the other side by the different-keypair control below.
     */
    @Test
    fun `a mutated public key verifies only when it is the same RSA key`() {
        val real = keyPair.public as RSAPublicKey
        val alphabet = ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=" +
            " \n!-_" + eAcute).toCharArray()
        val rnd = Random(KEY_MUTATION_SEED)
        var noop = 0
        var rejected = 0
        var acceptedAsSameKey = 0
        var acceptedWithDifferentBytes = 0

        repeat(KEY_MUTATIONS) {
            val i = rnd.nextInt(publicKeyBase64.length)
            val mutated = publicKeyBase64.substring(0, i) +
                alphabet[rnd.nextInt(alphabet.size)] +
                publicKeyBase64.substring(i + 1)
            // The replacement can be the character already there. Such a case is not a mutation
            // at all and must not be counted as an acceptance, or the controls below would be
            // satisfied by the real key verifying itself — which is what they exist to rule out.
            if (mutated == publicKeyBase64) {
                noop++
                return@repeat
            }
            if (!Utils.verifySignature(mutated, NONCE, signature)) {
                rejected++
                return@repeat
            }
            val decoded = try {
                Base64.decode(mutated, Base64.DEFAULT)
            } catch (_: Exception) {
                ByteArray(0)
            }
            val parsed = parseRsaPublicKey(decoded)
                ?: throw AssertionError(
                    "a mutated public key verified a signature but does not parse as an RSA " +
                        "public key at all: mutation at index $i",
                )
            if (parsed.modulus != real.modulus || parsed.publicExponent != real.publicExponent) {
                throw AssertionError(
                    "a mutated public key verified a signature it should not have: the mutation " +
                        "at index $i decoded to a DIFFERENT RSA key (modulus " +
                        "${if (parsed.modulus == real.modulus) "same" else "differs"}, exponent " +
                        "${parsed.publicExponent} vs ${real.publicExponent})",
                )
            }
            acceptedAsSameKey++
            if (!decoded.contentEquals(keyPair.public.encoded)) acceptedWithDifferentBytes++
        }

        assertTrue(
            "control: most mutations must actually be rejected, else this proves nothing; " +
                "rejected $rejected of $KEY_MUTATIONS ($noop were no-ops), $acceptedAsSameKey " +
                "were the same key, $acceptedWithDifferentBytes of those under different bytes",
            rejected > KEY_MUTATIONS / 2,
        )
        // The branch this test was rewritten for. Counting acceptances is not enough: an
        // acceptance under *identical* bytes proves nothing about key identity, so the floor is
        // on the different-bytes case specifically, which is the only one where "same bytes" and
        // "same key" could have disagreed. Measured at exactly 1 across 30 freshly generated
        // keypairs — it falls out of the seeded position sequence, not out of any one key — so
        // the floor is `> 0` rather than a count, and it is not flaky.
        assertTrue(
            "control: at least one mutation must be accepted under bytes that differ from the " +
                "real key, else the same-key check never runs on the case that motivates it; " +
                "got $acceptedWithDifferentBytes (of $acceptedAsSameKey accepted). Like the OID " +
                "test's own floor, this goes to zero if a JCE provider ever tightens KeyFactory " +
                "against non-rsaEncryption OIDs — that would be a deliberate platform change, " +
                "and the fix is to revisit both tests rather than to lower this floor",
            acceptedWithDifferentBytes > 0,
        )
    }

    /**
     * The finding that forced the test above to be phrased over the key rather than the bytes,
     * pinned by name so a future reader meets it as a statement rather than as a fuzz failure.
     *
     * Byte 16 of an X.509-encoded RSA public key is the last arc of the `rsaEncryption` OID
     * `1.2.840.113549.1.1.1`. The JCE's RSA [KeyFactory] does not hold the caller to that arc:
     * a key wrapped in `1.1.2`, `1.1.5`, `1.1.11` or `1.1.15` — OIDs that name *signature*
     * algorithms, not `rsaEncryption` — parses anyway, yields the identical modulus and public
     * exponent, and verifies the identical signature.
     *
     * This is not an authentication weakness: every one of these is the *same* key, and the
     * different-keypair control below is what says a different key never verifies. It is an
     * **identity-matching** hazard, and it is the same shape as the one [Utils.validateEntry]
     * documents for stray characters: the protocol identifies a profile by the public-key
     * *string* and the vault looks it up by equality, so one key can have several spellings
     * that all authenticate but only one of which will ever find a profile. Narrowing what
     * [Utils.verifySignature] accepts is a change to the algorithms it honours and therefore a
     * human's decision, so this test records the behaviour rather than changing it.
     */
    @Test
    fun `a key whose AlgorithmIdentifier OID was mutated is still the same RSA key`() {
        val real = keyPair.public as RSAPublicKey
        val encoded = keyPair.public.encoded

        assertEquals(
            "byte 16 should be the last arc of the rsaEncryption OID; if this moved, the arcs " +
                "below are no longer mutating what this test claims they are",
            1,
            encoded[OID_LAST_ARC_INDEX].toInt(),
        )

        var verified = 0
        listOf(2, 5, 10, 11, 15).forEach { arc ->
            val variant = encoded.copyOf()
            variant[OID_LAST_ARC_INDEX] = arc.toByte()
            val variantBase64 = Base64.encodeToString(variant, Base64.DEFAULT)

            // No "the encoding actually changed" control here: byte 16 is asserted to be 1 above
            // and none of the arcs is 1, so such a check could not fail and would be decoration.
            val parsed = parseRsaPublicKey(variant)
            if (parsed == null) return@forEach
            assertEquals("OID arc $arc parsed to a different modulus", real.modulus, parsed.modulus)
            assertEquals(
                "OID arc $arc parsed to a different public exponent",
                real.publicExponent,
                parsed.publicExponent,
            )
            if (Utils.verifySignature(variantBase64, NONCE, signature)) verified++
        }
        assertTrue(
            "the point of this test is that at least one non-rsaEncryption OID still verifies; " +
                "if none does, the JCE became strict and the sibling test's wording should be " +
                "revisited (got $verified)",
            verified > 0,
        )
    }

    /**
     * The property the two tests above exist to protect, stated directly: a genuinely different
     * keypair never verifies a signature it did not make.
     */
    @Test
    fun `a different keypair never verifies the genuine signature`() {
        repeat(3) {
            val other = KeyPairGenerator.getInstance("RSA")
                .apply { initialize(2048) }
                .generateKeyPair()
            assertTrue(
                "a different RSA keypair verified a signature made by another key",
                !Utils.verifySignature(
                    Base64.encodeToString(other.public.encoded, Base64.DEFAULT),
                    NONCE,
                    signature,
                ),
            )
        }
    }

    private fun parseRsaPublicKey(bytes: ByteArray): RSAPublicKey? = try {
        KeyFactory.getInstance("RSA").generatePublic(X509EncodedKeySpec(bytes)) as? RSAPublicKey
    } catch (_: Exception) {
        null
    }

    companion object {
        /** Arbitrary; what matters is only that it never changes. */
        private const val MASTER_SEED = 0x4C494D20543801L
        private const val KEY_MUTATION_SEED = 0x4C494D20543802L
        private const val CASES = 3000
        private const val KEY_MUTATIONS = 500
        private const val PAYLOAD_PREVIEW = 2000
        private const val HEX = "0123456789abcdef"

        /**
         * A correlation token the corpus cannot produce: no mutation of the well-formed
         * payloads emits it, so "matched" and "is the expected code" cannot coincide by luck.
         */
        private const val KNOWN_CODE = "req-known-0e3f"

        /** A fixed clock, so the freshness arm means the same thing on every run. */
        private const val FUZZ_CLOCK = 1_770_000_000_000L

        /**
         * Offset of the last arc of the `rsaEncryption` OID inside an X.509-encoded RSA public
         * key: `30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 [01] 05 00 03 ...`. Asserted
         * before it is relied on.
         */
        private const val OID_LAST_ARC_INDEX = 16

        /**
         * See `the corpus is byte-identical on every run`. This is a change-detector, not one
         * of the safety assertions: it catches an *accidental* edit to the generator, which
         * would silently swap the corpus for a different one and make every earlier failure
         * report in the log unreproducible. Recomputing it is correct when the generator was
         * edited on purpose, and wrong every other time.
         */
        private const val CORPUS_DIGEST =
            "d54e1fce3325c7e92892f49fc7e34584e8a0a53901c5f327bc09ad532a411b01"

        /**
         * Bytes chosen so that no `String` can encode to them: 0x81 and its neighbours appear as
         * bare UTF-8 continuation bytes. Pinned by `the challenge nonce is unreachable from any
         * text payload`.
         */
        private val NONCE = ByteArray(32) { (it * 7 + 3).toByte() }

        private lateinit var keyPair: KeyPair
        private lateinit var publicKeyBase64: String
        private lateinit var signature: ByteArray

        /** 2048-bit RSA generation is slow (~100ms); do it once for the whole class. */
        @JvmStatic
        @BeforeClass
        fun generateKeys() {
            keyPair = KeyPairGenerator.getInstance("RSA")
                .apply { initialize(2048) }
                .generateKeyPair()
            publicKeyBase64 = Base64.encodeToString(keyPair.public.encoded, Base64.DEFAULT)
            signature = Signature.getInstance("SHA256withRSA").run {
                initSign(keyPair.private)
                update(NONCE)
                sign()
            }
        }

        private fun hex(bytes: ByteArray): String = buildString(bytes.size * 2) {
            bytes.forEach { b ->
                val v = b.toInt() and 0xFF
                append(HEX[v shr 4])
                append(HEX[v and 0xF])
            }
        }
    }
}
